name: CI/CD pipeline

on:
  push:
    branches:
      - lab11
  workflow_dispatch:
    
env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: infra

      - name: Provision infrastructure
        uses: pulumi/actions@v4.2.1
        with:
          command: up
          stack-name: teachingiac/vue-2048-mk-mk/dev
          work-dir: infra
          env:
            PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
      
      - name: Build package
        run: | 
          pnpm install
          pnpm build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
            name: ${{env.BUILD_ARTIFACT_NAME}}
            path: dist/

  # deploy-app:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Fetch build artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: ${{env.BUILD_ARTIFACT_NAME}}
  #         path: ${{github.workspace}}
  #     - name: Deploy to PROD
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  #         action: "upload"
  #         app_location: ${{github.workspace}}
  #         skip_app_build: true
