name: GitHub Actions pipeline
on:
    push:
      branches:
        - lab9
        - main
    pull_request:
      branches:
        - lab9
        - main
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            path: '.'
        - name: cache
          uses: actions/cache@v2
          with:
            path: |
              node_modules/ 
        - name: install pnpm
          run: |
            curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
            pnpm config set store-dir .pnpm-store  
        - name: build
          run: |
              pnpm install
              pnpm build
        - name: static-analysis
          run: |
            pnpm type-check
            pnpm lint
                
        - name: unit-test
          run: |
            pnpm test  
